name: gridfind
description: path finding algorithms for 2D grid
version: 0.1.0-alpha
repository: https://github.com/MikulasBar/gridfind

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
