name: gridfind
description: path finding algorithms for 2D grid and graph
version: 0.3.0
repository: https://github.com/MikulasBar/gridfind

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.15
